import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { CountrySelector } from "@/components/CountrySelector";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const geist = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${geist.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <header className="border-b border-gray-200 bg-white">
            <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex justify-between items-center h-16">
                <div className="flex items-center">
                  <h1 className="text-xl font-bold text-gray-900">
                    MediaSyndicate
                  </h1>
                </div>
                <div className="flex items-center space-x-4">
                  <CountrySelector />
                </div>
              </div>
            </nav>
          </header>
          <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            {children}
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

